//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saudi_Auctions.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.VehicleImages = new HashSet<VehicleImage>();
        }
    
        public decimal Id { get; set; }
        public string Model { get; set; }
        public string Title { get; set; }
        public string MobileNo { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public string Description { get; set; }
        public string Kilometers { get; set; }
        public string BodyCondition { get; set; }
        public string MechanicalCondition { get; set; }
        public Nullable<int> Year { get; set; }
        public string VIN { get; set; }
        public string BodyType { get; set; }
        public string Color { get; set; }
        public string TransmissionType { get; set; }
        public string RegionalSpecs { get; set; }
        public Nullable<int> NoOfCylinders { get; set; }
        public Nullable<int> Doors { get; set; }
        public string HorsePower { get; set; }
        public string Waranty { get; set; }
        public string FuelType { get; set; }
        public string Location { get; set; }
        public string ReportName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleImage> VehicleImages { get; set; }
    }
}
