//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saudi_Auctions.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModel
    {
        public decimal VehicleModelId { get; set; }
        public string ModelText { get; set; }
        public Nullable<int> ModelValue { get; set; }
        public string Type { get; set; }
    }
}
