//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saudi_Auctions.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleImage
    {
        public decimal Id { get; set; }
        public string ImageName { get; set; }
        public decimal VechicleId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
